---
- name: Patching Centos Linux System
  hosts: all
  ignore_errors: yes

  tasks:
   - name: Update all packages on the server
     yum:
      name: '*'
      state: latest

   - name: Reboot a slow machine that might have lots of updates to apply
     shell: sleep 10 && /sbin/shutdown -r now
     async: 300
     poll: 0
     become: true

   - name: Wait for the server to finish rebooting
     wait_for_connection:
       delay: 15
       sleep: 15
       timeout: 300
