---
- name: Patching Centos Linux System
  hosts: all
  ignore_errors: yes

  tasks:
   - name: upgrade all packages on the server
     yum:
      name: '*'
      state: latest
     when: app_process_check.stdout == ansible_distribution == ‘CentOS’ or ansible_distribution == ‘Red Hat Enterprise Linux’
     register: yum_update

   - name: Check if reboot required after kernel update.
     shell: KERNEL_NEW=$(rpm -q –last kernel |head -1 | awk ‘{print $1}’ | sed ‘s/kernel-//’); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo “reboot_needed”; else echo “reboot_not_needed”; fi
     ignore_errors: true
     register: reboot_required

   - name: Restart system
     command: shutdown -r +1 “Rebooting System After Patching”
     async: 0
     poll: 0
     when: reboot_required.stdout == “reboot_needed”
     register: reboot_started
     ignore_errors: true

   - name: wait for 3 minutues for system to come up after the reboot
     pause:
     minutes: 3

   - name: check if system is up and responding to ssh
     local_action:
     module: wait_for
       host=all
       port=22
       delay=15
       timeout=300
       state=started
     when: reboot_started|changed
