---
- name: Patching Centos Linux System
  hosts: all
  ignore_errors: yes

  tasks:
   - name: Running prepatch info commands
     shell: |
       df -hP
       cat /etc/resolv.conf
       ntpstat
     register: prepatch
     ignore_errors: True

   - name: Removing old prepatch info file
     local_action: file path={{ playbook_dir }}/{{ inventory_hostname }}-prepatch.txt state=absent

   - name: storing prepatch info
     local_action: copy content={{ prepatch.stdout }} dest={{ playbook_dir }}/{{ inventory_hostname }}-prepatch.txt
     
   - name: Upgrade all packages
     yum:
       name: '*'
       state: latest

   - name: Restart server after patching
     command: /sbin/reboot
     async: 0
     poll: 0
     ignore_errors: true

   - name: Pause for 180 seconds
     pause: minutes=3

   - name: Wait for the server to restart
     local_action: wait_for host={{ inventory_hostname }}
                   port=22
                   delay=15
                   timeout=300
                   state=started
                   connect_timeout=15

   - name: Restarting NTP SERVER
     service:
       name: ntpd
       state: restarted
       enabled: yes

   - name: Running postpatch info commands
     shell: |
       df -hP
       cat /etc/resolv.conf
       sleep 10
       ntpstat
     register: postpatch
     ignore_errors: True

   - name: Removing old postpatch info file
     local_action: file path={{ playbook_dir }}/{{ inventory_hostname }}-postpatch.txt state=absent

   - name: Storing postpatch info
     local_action: copy content={{ postpatch.stdout }} dest={{ playbook_dir }}/{{ inventory_hostname }}-postpatch.txt
